sudo: required

language: generic

deploy:
- provider: script
  script: git fetch && git push https://$AZURE_WA_USERNAME:$AZURE_WA_PASSWORD@$AZURE_WA_SITE.scm.azurewebsites.net:443/$AZURE_WA_SITE.git HEAD:refs/heads/master
  on: 
   branch: development